[package]
name = "unicode_sec"
version = "0.1.0"
authors = ["stermonzl"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
unicode-security = "0.0.5"
colored = "2.0.0"
substring = "1.4.5"